# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: housekeeper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11housekeeper.proto\x12\x0bhousekeeper\x1a\x1bgoogle/protobuf/empty.proto\"M\n\x0bHouseKeeper\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfirstName\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"G\n\x11HouseKeeperCreate\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\"S\n\x11HouseKeeperUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfirstName\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x92\x03\n\x12HouseKeeperService\x12H\n\x12GetAllHouseKeepers\x12\x16.google.protobuf.Empty\x1a\x18.housekeeper.HouseKeeper0\x01\x12\x45\n\x11GetOneHouseKeeper\x12\x16.housekeeper.IdRequest\x1a\x18.housekeeper.HouseKeeper\x12M\n\x11\x43reateHouseKeeper\x12\x1e.housekeeper.HouseKeeperCreate\x1a\x18.housekeeper.HouseKeeper\x12Q\n\x15UpdateByIdHouseKeeper\x12\x1e.housekeeper.HouseKeeperUpdate\x1a\x18.housekeeper.HouseKeeper\x12I\n\x15\x44\x65leteByIdHouseKeeper\x12\x16.housekeeper.IdRequest\x1a\x18.housekeeper.HouseKeeperb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'housekeeper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HOUSEKEEPER']._serialized_start=63
  _globals['_HOUSEKEEPER']._serialized_end=140
  _globals['_HOUSEKEEPERCREATE']._serialized_start=142
  _globals['_HOUSEKEEPERCREATE']._serialized_end=213
  _globals['_HOUSEKEEPERUPDATE']._serialized_start=215
  _globals['_HOUSEKEEPERUPDATE']._serialized_end=298
  _globals['_IDREQUEST']._serialized_start=300
  _globals['_IDREQUEST']._serialized_end=323
  _globals['_HOUSEKEEPERSERVICE']._serialized_start=326
  _globals['_HOUSEKEEPERSERVICE']._serialized_end=728
# @@protoc_insertion_point(module_scope)
